AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Streaming Bedrock Response with FastAPI on AWS Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Parameters:
  OpenAIAPIKey:
    Type: String
    Description: OpenAI API Key
    Default: 1
  OpenAIBaseUrl:
    Type: String
    Description: OpenAI Base URL
    Default: 1
  GeminiAPIKey:
    Type: String
    Description: Gemini API Key
    Default: 1
  S3TempBucketName:
    Type: String
    Description: Name of the temporary S3 bucket
    Default: 1

Resources:
  GenerativeUIAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          OPENAI_API_KEY: !Ref OpenAIAPIKey
          GEMINI_API_KEY: !Ref GeminiAPIKey
          OPENAI_BASE_URL: !Ref OpenAIBaseUrl
          S3_TEMP_BUCKET_NAME: !Ref S3TempBucketName
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      Policies:
      - Statement:
        - Sid: BedrockInvokePolicy
          Effect: Allow
          Action:
            - bedrock:InvokeModelWithResponseStream
          Resource: '*'
        - Sid: AllObjectActions
          Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - !Sub 'arn:aws:s3:::${S3TempBucketName}/*'
      Tracing: Active
    Metadata:
      DockerContext: server
      Dockerfile: ../docker/Dockerfile.aws.lambda
      DockerTag: v1


Outputs:
  GenerativeUIAPIFunctionUrl:
    Description: "Function URL for FastAPI function"
    Value: !GetAtt GenerativeUIAPIFunctionUrl.FunctionUrl
  GenerativeUIAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt GenerativeUIAPIFunction.Arn