version = 0.1
[default.deploy.parameters]
stack_name = "generative-ui-preview"
resolve_s3 = true
s3_prefix = "generative-ui-preview"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
[preview.deploy.parameters]
stack_name = "generative-ui-preview"
resolve_s3 = true
s3_prefix = "generative-ui-preview"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["GenerativeUIAPIFunction=654654285942.dkr.ecr.ap-southeast-1.amazonaws.com/generativeuipreviewd29dd6a7/generativeuiapifunction5d6c99d2repo"]
